[package]
name = "mecatol-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "mecatol"
path = "src/main.rs"

[dependencies]
mecatol-core = { workspace = true }
mecatol-standards = { workspace = true }
mecatol-engine = { workspace = true }
